dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g angular-cli
script:
  - ng serve
  - ng tests --watch=false
  - ng e2e

notifications:
  email: true